services:
  - type: web
    name: how-much-you-know-whom
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATA_DIR
        value: /var/data
    disk:
      name: quiz-data
      mountPath: /var/data
      sizeGB: 1
